name: muse_wave
description: "A new Flutter project."
version: 1.0.4+10400

environment:
  sdk: ^3.7.0
dependency_overrides:
  video_player_android: 2.7.1
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


  device_info_plus: ^10.1.0
  get: ^4.7.2
  logger: ^2.5.0
  path_provider: ^2.1.5
  hive: ^2.2.3
  package_info_plus: ^8.3.0
  uuid: ^4.5.1
  android_intent_plus: ^5.3.0
  shared_preferences: ^2.5.1
  file_picker: ^10.1.2
  appsflyer_sdk: ^6.15.2
  audio_metadata_reader: ^1.1.0
#  flutter_media_metadata: ^1.0.0+1
  audioplayers: ^6.2.0
  app_settings: ^5.2.0
  text_scroll: ^0.2.0
  flutter_slidable: ^4.0.0
  flutter_sound: ^9.24.5
  audio_service: ^0.18.17
  audio_session: ^0.1.25
  permission_handler: ^11.4.0
  bot_toast: ^4.1.3
  flutter_screenutil: ^5.9.3
  webview_flutter: ^4.10.0
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  easy_refresh: ^3.4.0

  connectivity_plus: ^6.0.3
  dio: ^5.7.0
  cached_network_image: ^3.3.1
  video_player: 2.8.7
#  video_player_media_kit: ^1.0.5
#  media_kit_libs_android_video: ^1.0.5

  extended_wrap: ^0.1.5
  #  al_downloader: ^1.8.4
  visibility_detector: ^0.4.0+2
  scroll_to_index: ^3.0.1
  encrypt: ^5.0.3

  android_id: ^0.4.0
  advertising_id: ^2.6.0
  android_play_install_referrer: ^0.4.0
  google_mobile_ads: ^6.0.0
  applovin_max: ^4.4.0
  anythink_sdk:
    path: plugin/anythink_sdk-1.0.5
#  anythink_sdk: ^1.0.8
#  secmtp_sdk: ^1.0.8


  facebook_app_events:
    git:
      url: https://github.com/oddbit/flutter_facebook_app_events/
      ref: e5bab0a
  firebase_core: ^3.6.0
  firebase_remote_config: ^5.1.3
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.1.3
#  firebase_performance: ^0.10.0+8
  flutter_local_notifications: ^18.0.1
  flutter_rating_bar: ^4.0.1
  #flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/img/logo.png"
  image_path_ios: "assets/img/logo.png"
  adaptive_icon_background:  "assets/img/logo_b.png"
  adaptive_icon_foreground: "assets/img/logo_f.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/oimg/
